if(NOT EXISTS "${RUNNER}" OR NOT DEFINED WORK OR WORK STREQUAL "")
    message(FATAL_ERROR "Desktop runner test requires RUNNER and WORK paths")
endif()

string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(directory "${WORK}/native-${suffix}")
if(EXISTS "${directory}")
    message(FATAL_ERROR "Desktop test directory already exists: ${directory}")
endif()
file(MAKE_DIRECTORY "${directory}")

# These files only exercise media loading and process I/O. Paused execution
# never runs the deliberately synthetic cartridge or firmware instructions.
string(ASCII 128 55 18 64 magic)
string(REPEAT "E" 4084 cartridge_body)
string(REPEAT "P" 1984 firmware)
set(cartridge "${directory}/測試 cartridge.z64")
set(pif "${directory}/啟動 firmware.rom")
set(save "${directory}/儲存 data.sra")
set(preferences "${directory}/設定 preferences.conf")
file(WRITE "${cartridge}" "${magic}EEEEEEED${cartridge_body}")
file(WRITE "${pif}" "${firmware}")

set(ENV{SDL_VIDEO_DRIVER} dummy)
set(ENV{SDL_AUDIO_DRIVER} dummy)
set(arguments "${cartridge}" --pif "${pif}" --region ntsc --pif-region ntsc
    --cic 6102 --save sram32 --save-file "${save}" --accessory 1:none
    --preferences "${preferences}" --renderer software --paused --run-for 0.05)

foreach(pass RANGE 1 2)
    string(REPEAT "${pass}" 32768 saved_bytes)
    file(WRITE "${save}" "${saved_bytes}")
    file(SHA256 "${save}" saved_hash)
    set(capture "${directory}/畫面 ${pass}.bmp")
    if(pass EQUAL 2)
        set(ENV{SDL_AUDIO_DRIVER} cupid-invalid-audio-driver)
    endif()
    execute_process(COMMAND "${RUNNER}" ${arguments} --capture "${capture}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 15)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Desktop Unicode/restart pass ${pass} failed: ${result}\n${output}\n${errors}")
    endif()
    file(SHA256 "${save}" actual_hash)
    if(NOT actual_hash STREQUAL saved_hash)
        message(FATAL_ERROR "Desktop restart changed the retained save bytes")
    endif()
    if(NOT EXISTS "${preferences}" OR NOT EXISTS "${capture}")
        message(FATAL_ERROR "Desktop did not create Unicode settings and capture paths")
    endif()
    file(READ "${capture}" signature LIMIT 2 HEX)
    if(NOT signature STREQUAL "424d")
        message(FATAL_ERROR "Desktop capture is not a BMP file")
    endif()
    if(NOT output MATCHES "instructions=0")
        message(FATAL_ERROR "Paused desktop runner executed the synthetic cartridge\n${output}")
    endif()
endforeach()

file(WRITE "${capture}" "previous capture")
execute_process(COMMAND "${RUNNER}" ${arguments} --capture "${capture}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 15)
if(NOT result EQUAL 1)
    message(FATAL_ERROR "An occupied capture path did not fail with exit code 1: ${result}\n${output}\n${errors}")
endif()
file(READ "${capture}" retained_capture)
if(NOT retained_capture STREQUAL "previous capture")
    message(FATAL_ERROR "Desktop overwrote an existing capture")
endif()

message(STATUS "Desktop Unicode arguments, save restart, unavailable audio, and capture protection passed")
file(REMOVE_RECURSE "${directory}")
