include(CheckIPOSupported)

option(CUPID_INTERPROCEDURAL_OPTIMIZATION "Optimize across source files in release builds" ON)
if(CUPID_INTERPROCEDURAL_OPTIMIZATION)
  check_ipo_supported(RESULT cupid_ipo_supported OUTPUT cupid_ipo_output LANGUAGES C CXX)
  if(cupid_ipo_supported)
    if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
      set(CMAKE_C_LINK_OPTIONS_IPO /LTCG)
    endif()
    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
      set(CMAKE_CXX_LINK_OPTIONS_IPO /LTCG)
      add_link_options("$<$<CONFIG:Release,RelWithDebInfo,MinSizeRel>:/LTCG>")
    endif()
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO TRUE)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_MINSIZEREL TRUE)
  else()
    message(STATUS "Interprocedural optimization is unavailable for this compiler")
    message(DEBUG "${cupid_ipo_output}")
  endif()
endif()
