include(CheckIPOSupported)

option(CUPID_INTERPROCEDURAL_OPTIMIZATION "Optimize across source files in release builds" ON)
if(CUPID_INTERPROCEDURAL_OPTIMIZATION)
  check_ipo_supported(RESULT cupid_ipo_supported OUTPUT cupid_ipo_output LANGUAGES C CXX)
  if(cupid_ipo_supported)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO TRUE)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_MINSIZEREL TRUE)
  else()
    message(STATUS "Interprocedural optimization is unavailable for this compiler")
    message(DEBUG "${cupid_ipo_output}")
  endif()
endif()
