set(CUPID_IPO_SUPPORTED FALSE)
if(CUPID_IPO AND NOT CUPID_SANITIZERS)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT CUPID_IPO_SUPPORTED OUTPUT CUPID_IPO_ERROR LANGUAGES CXX)
    if(CUPID_IPO_SUPPORTED)
        message(STATUS "Interprocedural optimization enabled for release targets")
    else()
        message(STATUS "Interprocedural optimization unavailable; using normal compilation: ${CUPID_IPO_ERROR}")
    endif()
endif()
