set(renderer_state_sources "${CMAKE_CURRENT_BINARY_DIR}/renderer-state/parallel-rdp")
file(MAKE_DIRECTORY "${renderer_state_sources}")
file(COPY "${renderer_rdp_SOURCE_DIR}/parallel-rdp/" DESTINATION "${renderer_state_sources}")
foreach(header rdp_device rdp_renderer video_interface)
  set(path "${renderer_state_sources}/${header}.hpp")
  file(READ "${path}" content)
  set(namespace_marker "namespace RDP\n{")
  set(access_marker "private:\n")
  string(FIND "${content}" "${namespace_marker}" namespace_position)
  string(FIND "${content}" "${access_marker}" access_position)
  if(namespace_position LESS 0 OR access_position LESS 0)
    message(FATAL_ERROR "Renderer state access no longer matches the pinned ${header} interface")
  endif()
  string(REPLACE "${namespace_marker}"
    "namespace cupid::n64 { class RendererState; }\n\n${namespace_marker}" content "${content}")
  string(REPLACE "${access_marker}"
    "private:\n\tfriend class ::cupid::n64::RendererState;\n" content "${content}")
  file(WRITE "${path}" "${content}")
endforeach()
